### PR TITLE
Create German.lang

### PR DESCRIPTION
**Pull request by neocromicon**
It's not 100% perfect, i need see this ingame ;) :P

### CODE REVIEW

**Comment by IgorTimofeev** [comment]
Sounds great, but installer localization means necessity to localize the OS itself, i.e. during OS install it will register the selected language in the system config. Without MineOS/System/Localizations/German.lang it won't even boot

**Comment by neocromicon** [comment]
OK is in progress ;)

**Comment by CoolCat467** [comment]
Did you ever finish @neocromicon ?

**Comment by neocromicon** [comment]
> Did you ever finish @neocromicon ?

No...

**Comment by IgorTimofeev** [comment]
@CoolCat467 

image

**Pull request closed without merging**
