### PR TITLE
Chinese localization.

### PR DESCRIPTION
**Pull request by kebufu**

### CODE REVIEW

**Comment by IgorTimofeev** [comment]
I wonder if this will be the first of the last 5 pull requests that won't break localization files? :D

**Comment by 493505110** [comment]
Other localized files are not affected, there are 2 "Applications/3D Prints.app/Localizations/Chinese.lang" in the Files.cfg , and I just deleted one of them
（Bing translation）

并不会影响其他的本地化文件，在Files.cfg里有2个"Applications/3D Print.app/Localizations/Chinese.lang"，我只是删掉了其中的一个

**Comment by IgorTimofeev** [comment]
Meow, the problem with previous PRs wasn't in affecting existing files, but in syntax errors in PR .lang files. People were just commiting broken code ._.

Btw thx for your work

**Comment by 493505110** [comment]
In which file is there a syntax error?
(Bing translation)

在哪个文件中有语法错误?

**Comment by kebufu** [comment]
WTF
QQ图片20210204101502

**Comment by 493505110** [comment]
TIM截图20210204101702

**Comment by IgorTimofeev** [comment]
That's known issue with wide unicode symbols in Screen library. Their support wasn't planned because of performance issues

**Comment by kebufu** [comment]
Hey, I found a fix way. just change `unicode.len` to `unicode.wlen`

**Comment by IgorTimofeev** [comment]
@kebufu This "fix way" is obvious, and has been known about it since the time the screen library was written. The problem is that checking for the width of a character through "wlen" will greatly slow down the graphics rendering. I have to do this for every "dirty pixel" in the screen buffer

It was a choice between speed and support for Chinese/Korean/Japanese wide symbols. And since I don't give a shit about them, then this system will not be implemented either

**Comment by MrFredber** [comment]
and isn't it possible to make use of unicode.len, and if the language is Chinese, then use univode.wlen?

**Comment by 493505110** [comment]
I have a idea,
if the language is Chinese/Korean/Japanese then use unicode.wlen else use unicode.len?

**Comment by IgorTimofeev** [comment]
@MrFredber @493505110 You guys are just geniuses, 100K IQ min. How could I not have thought of this myself? \*sarcasm\*

Screen library **doesn't fucking consider** characters lengths at all. It uses horizontal scanlines of pixels, where each subsequent one with similar same background/foreground color is added into a characters table. As soon as the buffer width/end of scanline is reached, the characters are being combined through a table.concat and drawn via single gpu.set call. If you want to consider charactes length - current speed will be fucked

**Comment by kebufu** [comment]
> @MrFredber @493505110 You guys are just geniuses, 100K IQ min. How could I not have thought of this myself? *sarcasm*
> 
> Screen library **doesn't fucking consider** characters lengths at all. It uses horizontal scanlines of pixels, where each subsequent one with similar same background/foreground color is added into a characters table. As soon as the buffer width/end of scanline is reached, the characters are being combined through a table.concat and drawn via single gpu.set call. If you want to consider charactes length - current drawing speed will be settled down

Hey,I found a way, just fill with space,auto remove when rendering.

**Comment by IgorTimofeev** [comment]
>Hey,I found a way, just fill with space,auto remove when rendering.

**Comment by CoolCat467** [comment]
You can't really do that. That would be happening every single time the screen updates, and that would be a mess and slow things down.

**Pull request merged**
