### PR TITLE
Full Spanish Translation

### PR DESCRIPTION
**Pull request by GasInfinity**
Configured all the language files and the installer config, also all the possible apps are translated

### CODE REVIEW

**Comment by IgorTimofeev** [comment]
Wow, nice job. Thanks for adding installer config links <3

**Comment by IgorTimofeev** [comment]
NO, NOT NICE, required commas \*here\* are missing:

image

The entire installer is fucked up. I hate co-development...

**Comment by IgorTimofeev** [comment]
It's "LocalizationS", not "Localization"...

image

Same shit in 3DPrint.app and Nanomachines:

image

**Comment by GasInfinity** [comment]
Sorry, I wanted to help, the next time I'll check all the files before the PR.

**Comment by IgorTimofeev** [comment]
Meow, don't worry, I've already fixed all this stuff. It's just sad

image

**Pull request merged**
