### PR TITLE
Add Screen filter API

### PR DESCRIPTION
**Pull request by Fox2Code**
The API use the fact that MineOS use a software buffer and allow to modify displayed colors with a `function` (Aka. filter)

It only calls the filter (If there is one) when `GPUProxySetBackground` or `GPUProxySetForeground` is called, taking advantage that MineOS try to reduce GPU calls as much as possible, making the filter called only when necessary

Because it only modify hardware calls, it doesn't affect the colors returned by `screen.copy`, `screen.get`, or any method that access the software based buffer.

This API add `Screen.getFilter()`, `Screen.setFilter(filter)`, and `Screen.resetFilter()`

Example of possible use of the API:
ScreenFilterAPI

BlueFilter.lua:
```lua
local screen = require("Screen")
local color = require("Color")
local function blueFilter(input)
  local r, g, b = color.integerToRGB(input)
  b = math.floor(b * 0.60)
  return color.RGBToInteger(r, g, b)
end
screen.setFilter(blueFilter)
```
ResetFilter.lua:
```lua
local screen = require("Screen")
screen.resetFilter()
```

Note: I also cleaned a bit the end of `update()` to make the code more readable, it's probably a bit more optimized, but not something significant enough to call this an "optimization".

### CODE REVIEW

**Comment by IgorTimofeev** [comment]
"Optimized", lolwut? You're fucking calling an extra filter function in EVERY GPU color operation. Function calls has the largest budget in mod (see Machine.lua in sources), even tables indexing is faster

Btw this can be solved by extra condition like "if filter then filter(...) else ..."

**Comment by Fox2Code** [comment]
KK, I undestand, OpenComputer is a real mess, as I was using an emulator with no perf limitation.
I read `Machine.lua` and didn't found the limitation, can you give me the line number please.
I was using MineOS optimisation, but I didn't know the opencomputer mod was **that** bad when calling methods.

**Comment by Fox2Code** [comment]
Found it:
https://github.com/MightyPirates/OpenComputers/blob/af2db43c53b9690fceabfb813987572bf2258db5/src/main/scala/li/cil/oc/server/machine/Machine.scala#L370
I will read a bit more the code to see how to more reduce calls costs

**Comment by Fox2Code** [comment]
Wait no it's the component invoke... Hum... I was searching the direct method call.

**Comment by IgorTimofeev** [comment]
Main IPS limitations are here:

https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/resources/assets/opencomputers/lua/machine.lua#L47

Next, every **checkDeadline** call belongs to "limited mod stuff"

Bro, I'm sorry if I'm being rude, your color filter idea is really nice. But... as "modification for OS", not "native OS" I just don't want to slow down an already slow system even more. For the same reason, we had to abandon the check for "wide" characters in the screen library for users from asia

**Comment by Fox2Code** [comment]
Well, the `if else` is a good idea, and also I was aware of the deadline, but didn't know method call were so disastrous.
I agree with you that this API should be a lot more optimized before being considered to be up-streamed.

I know you didn't wanted to be rude, it's just I wasn't aware of how stupid were the limitations of the open computer mod.

**Comment by Fox2Code** [comment]
The PR is converted to a draft until I find a way to make the screen to be faster.
I don't think there is a way to make display fast when a filter is enabled, but at least I can try.

**Comment by IgorTimofeev** [comment]
F bro

**Comment by Fox2Code** [comment]
Update: I found a way to implement screen filtering without modifying MineOS code. 
(which made this commit unnecessary to implement screen filtering)

Also thank for having taken the time to communicate with me.

**Comment by IgorTimofeev** [comment]
> Update: I found a way to implement screen filtering without modifying MineOS code

Interesting, what's your solution? Semi-transparent GHI.panel? I'm out of ideas :D

**Pull request closed without merging**
