### PR TITLE
Fix bug #331

### PR DESCRIPTION
**Pull request by kebufu**

### CODE REVIEW

**Comment by IgorTimofeev** [comment]
Your "fix" is a bug itself:

image

And GPUProxy.bind shouldn't be used, because of screen buffer library has it's own wrapper for this functionality

**Comment by kebufu** [comment]
BTW, You cannot get resolution without bind screen,That why you get `Bad Argument #3` error on line 12.

**Comment by IgorTimofeev** [comment]
But GPU is already bound to the screen in OpenOS while running pastebin/wget command. Wtf are you talking about

**Comment by kebufu** [comment]
If we replace GPU/screen,We should re bind them.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月18日(星期天) 晚上7:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IgorTimofeev/MineOS] Fix bug #331 (#338)





 
But GPU is already bound to the screen in OpenOS while running pastebin/wget command. Wtf are you talking about

**Comment by IgorTimofeev** [comment]
OHHH WHO THE FUCK WILL DO IT? OKAY, IF YOU INSIST

**Comment by kebufu** [comment]
Oh,Thanks. Now we can install MineOS on OCEmu.

**Comment by IgorTimofeev** [comment]
> Now we can install MineOS on OCEmu
Does it finally have support of https protocol for downloading files from GitHub?

**Pull request merged**
