### PR TITLE
Move EEPROM flash stage to after-install

### PR DESCRIPTION
**Pull request by Def-Try**
yes

Related to #527

### CODE REVIEW

**Comment by PublicVoidUpdate** [comment]
May i ask what the benefit would be to move the eeprom flash stage to the end?

**Comment by Def-Try** [comment]
Check mentioned issue. In short: if you shutdown PC in mid-install it will not start install process again and OS will be broken and could not be booted up

**Comment by PublicVoidUpdate** [comment]
Oh, that's kinda cool

**Comment by CoolCat467** [comment]
Don't most install things say "Updating/Setting up, do not turn off computer please"? Maybe that would be better

**Comment by MrFredber** [comment]
yeah, but sudden power offs have not been canceled.

**Comment by Def-Try** [comment]
I broke my PC after exiting the game so...

**Pull request merged**
