### PR TITLE
Add a ton of localizations to almost everything

### PR DESCRIPTION
**Pull request by CoolCat467**
Add localization for almost everything google translate supports to all folders in Installer/Files.cfg if localization did not already exist.

Important: Because it is a machine translation, it is very likely terrible, but my thinking is have the base idea there, and people who use the languages can fix machine translation.

Everything is possible with a major update to my tool, https://github.com/CoolCat467/Localization-Translation-Utility

### CODE REVIEW

**Comment by IgorTimofeev** [comment]
Again? I thought we've already discussed this... Bro, I know it took your time and stuff, but

1) Installer will be fucked up. Need to add searching feature for exact language instead of listbox scrilling, because it's just too much languages. It allso need feature to select several languages from the list instead of "installing all of them", because installation time would take years (any maybe won't fit in 3.5 MB HDD)

2) Entire OS with dynamic lang changing will be fucked up. Need to add feature of downloading additional lang packs in App Market, when system language is being changed in runtime. Moreower, language changing needs to be deeply integrated with OS with downloading missing lang files (maybe in some sort of universal library for Installer/App Market). In utopian world, it should download missing lang files for all installed apps as well

3) Need to rewrire App Market DB/API as replacement to Files.cfg with some automations. I originally planned to support 2-4 system languages, because "yo dudes this is fucking minecraft no one needs hindi here". For this config was enough, but now it become inadequate:

image

4) Lang packs adding/editing would be fucked up and just inconvenient. For example, if I add "Games" section to App Market, I need to add corresponding lang string in English, then run pythong converter... but what would happen with existring lang files? Google translate is inaccurate, would it replace correct ones in working directory? Or it will just add missing lang key to them?

Ironic, but I've faced similar problem at work couple of years ago and have to write a small localization tool integrated with master DB that stores all translations & languages:

image

And then I don’t think that working in external software is particularly convenient, but there is simply no other way out if there are over 10 languages. How to deal with it in Minecraft?

**Comment by CoolCat467** [comment]
Would it be better if I added languages that installer supports, but app does not have translation for currently? Instead of 90+ ?

**Comment by IgorTimofeev** [comment]
Idk bro, both solutions sucks for such tiny project :(

**Comment by CoolCat467** [comment]
I think I'll leave this for if anything is changed in the future, but for the moment I'm going to open a second pull request that adds translations for languages supported in other places but don't exist for a particular app.

**Comment by IgorTimofeev** [comment]
Okay, if you want to. I'm not against hundreds of languages, I'm against the inconvenience of working with them. So sorry bro, hope this work won't be lost

**Pull request closed without merging**
