### PR TITLE
Create German.lang

### PR DESCRIPTION
**Pull request by neocromicon**
This is a awesome project and this is my chance to translate it to german :P

### CODE REVIEW

**Comment by CoolCat467** [comment]
German appears to already be supported.

**Comment by CoolCat467** [comment]
Plus, this is only the installer's language file. You're missing the big one that actually has everything in it. Additionally, the file is in the wrong place, and the information in it is no longer up to date.

**Comment by CoolCat467** [comment]
@neocromicon You can probably close this request, unless the most current version has grammatical issues or something, but even then you should really open a new request for that.

**Comment by IgorTimofeev** [comment]
Мешает, сука

**Pull request closed without merging**
