### PR TITLE
Attempt to add variable shapeLimit.

### PR DESCRIPTION
**Pull request by CoolCat467**
Implements suggested changes from issue #327

### CODE REVIEW

**Comment by CoolCat467** [comment]
IMPORTANT: Code is untested, and may not work. Hopefully it does though.

**Comment by IgorTimofeev** [comment]
\> Code is untested, and may not work
\> Pull request

image

**Comment by IgorTimofeev** [comment]
First, of course code won't work. Shape limit is a **local** variable, and it won't be visible in lower code:

image

Second, and more importantly, the original program has support for dynamically connecting/disconnecting components. That is, you can connect a 3D printer at runtime, which will enable printing feature & update UI. The entry point is here:

image

Your check for a 3D printer availability just breaks this logic. Therefore, it is also required to add functionality to update the list of shapes buttons.

**Comment by CoolCat467** [comment]
Ok, that makes sense, there definitely should be a handler added that updates shape limit on add and remove of 3d printer components. How would one go about updating the model's size then?

**Comment by IgorTimofeev** [comment]
Bruh...

image

**Comment by IgorTimofeev** [comment]
OKAY

**Pull request merged**
